### PR TITLE
CU-8j90d3 base code

### PR DESCRIPTION
**Pull request by Bernix01**

### CODE REVIEW

**Comment by Bernix01** [comment]
Task linked: [CU-8j90d3 Inicializar y configurar ambiente Móvil Residentes](https://app.clickup.com/t/8j90d3)

**Comment by Bernix01** [comment]
@whugo43 please add GitHub actions for automated testing and move the project file to the root directory

**Comment by Bernix01** [comment]
CI is failing please check that the lint script is added to the `package.json` scripts section. Also there are some merging conflicts that must be resolved. @whugo43

**Review by Oswagui — APPROVED** [review]
Clone without problems
Test chek in teams meetting.
General check in teams meeting.
Recomendation to Readme conflict.

**Pull request merged**
